services:
  db:
    container_name: webhook-db
    image: postgres:17
    environment:
      - POSTGRES_DB=webhook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - PGDATA=/data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webhook"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  db: