spring:
  application:
    name: webhook
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/webhook}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: validate
  Kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
  lifecycle:
    timeout-per-shutdown-phase: 80s
    task:
      scheduling:
        shutdown:
          await-termination: true
          await-termination-period: 80s

server:
  shutdown: graceful

webhook:
  dispatch: kafka

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always